# Configuração de Conexão com MySQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring3?useTimezone=true&serverTimezone=UTC   # URL de conexão com o MySQL
    username: root                         # Nome de usuário do MySQL
    password: root                            # Senha do usuário do MySQL
  jpa:
    hibernate:
      ddl-auto: update       # Estratégia para atualização automática do esquema do banco de dados
                             #(pode ser "update", "create", "create-drop", etc.)
                             #essa propriedade é responsavel em criar as tabalas no banco baseado nas entidades mapeadas,
                             #caso não queira criar atraves do jpa coloque como "none"
    show-sql: true           # Exibir consultas SQL no console (pode ser true ou false)
    database-platform: org.hibernate.dialect.MySQLDialect   # Dialeto do MySQL
