# Configuração de Conexão com MySQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring3?useTimezone=true&serverTimezone=UTC   # URL de conexão com o MySQL
    username: root                         # Nome de usuário do MySQL
    password: root                            # Senha do usuário do MySQL
  jpa:
    hibernate:
      ddl-auto: none       # Estratégia para atualização automática do esquema do banco de dados
                             #(pode ser "update", "create", "create-drop", etc.)
                             #essa propriedade é responsavel em criar as tabalas no banco baseado nas entidades mapeadas,
                             #caso não queira criar atraves do jpa coloque como "none"
    show-sql: true           # Exibir consultas SQL no console (pode ser true ou false)
    database-platform: org.hibernate.dialect.MySQLDialect   # Dialeto do MySQL

#Define quais paths serão expostos no swagger
#spring-doc:
#  paths-to-match:
#  - /person/**
#  - /book/**
# Ou pode usar assim a depender de como esta seu path
spring-doc:
  paths-to-match: /api/**/v1/**


  #Por exemplo, se a sua aplicação estiver em http://localhost:8080,
  #a interface do Swagger estará disponível em http://localhost:8080/swagger-ui/.
  #No entanto, se use-root-path estiver configurado como true,
  #ela estará disponível em http://localhost:8080/.
  swagger-ui:
    use-root-path: true

#usando cors no escopo global
cors:
  originPatterns: http://localhost:8080,http://localhost:3000

